config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title,
    uniqueness: true,
    presence: true

  validates :body,
    presence: true,
    length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = 'You have created book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:notice] = 'Book was successfully destroyed.'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p class="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <% if @book.errors.count==1 %>
            <h3><%= @book.errors.count %> error prohibited this book from being saved:</h2>
          <% else %>
            <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
          <% end %>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</p>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Option</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <% if @book.errors.count==1 %>
      <h3><%= @book.errors.count %> error prohibited this book from being saved:</h2>
    <% else %>
      <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <% end %>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'share/userinfo', user: current_user %> <!-- これはcurrentでOK -->
      <%= render 'share/newbook' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(50, 50) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <svg class="fas fa-sharp fa-heart fa-xs" style="color:red"></svg><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <svg class="fas fa-sharp fa-heart fa-xs" style="color:blue"></svg><%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= "#{book.book_comments.count} コメント" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <p>Title</p>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <p>Option</p>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'share/userinfo', user: @book.user %>
      <%= render 'share/newbook' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
  		  <tbody>
  		    <tr>
  		      <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(50, 50) %>
              <% end %>
              <br>
              <%= link_to user_path(@book.user.id) do %>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <svg class="svg-inline--fa fas fa-sharp fa-solid fa-heart fa-xs" style="color:red"></svg><%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <svg class="svg-inline--fa fas fa-sharp fa-solid fa-heart fa-xs" style="color:blue"></svg><%= @book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_33022" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger destroy_book_33176" %>
              </td>
            <% end %>
            <td>
              <%= "#{@book.book_comments.count} コメント" %>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
        <p>コメント件数：<%= @book.book_comments.count %></p>
        <% @book.book_comments.each do |book_comment| %>
          <div>
          <%= image_tag book_comment.user.get_profile_image(50,50) %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_33176" %>
          <% end %>
          </div>
          <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
        <% end %>
      </div>

      <%= form_with model: [@book, @book_comment] do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "送信" %>
        </div>
      <% end %>

    </div>
  </div>
</div>